# Generated by Django 3.2.7 on 2021-09-07 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('businesses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_module', to='app.business')),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('displayName', models.CharField(max_length=255)),
                ('filters', models.JSONField(blank=True, null=True)),
                ('created_by', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('report_id', models.CharField(blank=True, max_length=255, null=True)),
                ('filter_json', models.JSONField(blank=True, default=None)),
                ('page_tabs', models.BooleanField(default=False)),
                ('filter_pane', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('area', models.ManyToManyField(blank=True, related_name='area_report', to='app.Area')),
                ('business', models.ManyToManyField(blank=True, related_name='business_report', to='app.Business')),
                ('department', models.ManyToManyField(blank=True, related_name='department_report', to='app.Department')),
                ('module', models.ManyToManyField(blank=True, related_name='module_report', to='app.Module')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('workspace_id', models.CharField(max_length=255)),
                ('created_by', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(max_length=512)),
                ('user_id', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_plant', to='app.plant')),
                ('role', models.ManyToManyField(blank=True, related_name='user_role', to='app.Role')),
            ],
        ),
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('area', models.ManyToManyField(blank=True, related_name='area_stream', to='app.Area')),
                ('business', models.ManyToManyField(blank=True, related_name='business_stream', to='app.Business')),
                ('department', models.ManyToManyField(blank=True, related_name='department_stream', to='app.Department')),
                ('module', models.ManyToManyField(blank=True, related_name='module_stream', to='app.Module')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stream_plant', to='app.plant')),
                ('report', models.ManyToManyField(blank=True, related_name='report_stream', to='app.Report')),
            ],
        ),
        migrations.AddField(
            model_name='report',
            name='owner',
            field=models.ManyToManyField(blank=True, related_name='owner_report', to='app.User'),
        ),
        migrations.AddField(
            model_name='report',
            name='pages',
            field=models.ManyToManyField(blank=True, related_name='page_report', to='app.Page'),
        ),
        migrations.AddField(
            model_name='report',
            name='plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_plant', to='app.plant'),
        ),
        migrations.AddField(
            model_name='report',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_workspace', to='app.workspace'),
        ),
        migrations.CreateModel(
            name='Pod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('pod_id', models.CharField(max_length=255)),
                ('room_num', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('area', models.ManyToManyField(blank=True, related_name='area_pod', to='app.Area')),
                ('business', models.ManyToManyField(blank=True, related_name='business_pod', to='app.Business')),
                ('department', models.ManyToManyField(blank=True, related_name='department_pod', to='app.Department')),
                ('module', models.ManyToManyField(blank=True, related_name='module_pod', to='app.Module')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pod_plant', to='app.plant')),
                ('stream', models.ManyToManyField(blank=True, related_name='stream_pod', to='app.Stream')),
            ],
        ),
        migrations.AddField(
            model_name='module',
            name='plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_plant', to='app.plant'),
        ),
        migrations.AddField(
            model_name='department',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_department', to='app.module'),
        ),
        migrations.AddField(
            model_name='department',
            name='plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dept_plant', to='app.plant'),
        ),
        migrations.AddField(
            model_name='business',
            name='plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plant_business', to='app.plant'),
        ),
        migrations.AddField(
            model_name='area',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_area', to='app.department'),
        ),
        migrations.AddField(
            model_name='area',
            name='plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='area_plant', to='app.plant'),
        ),
    ]
