# Generated by Django 3.2.7 on 2021-09-07 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='filter_json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
