# Generated by Django 3.2.7 on 2021-09-14 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_stream_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=55)),
                ('color', models.CharField(default='white', max_length=55)),
                ('background', models.CharField(default='royalblue', max_length=55)),
                ('miniName', models.CharField(max_length=10)),
                ('path', models.URLField()),
                ('target', models.CharField(default='_blank', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='LinkWorkspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('area', models.ManyToManyField(blank=True, related_name='area_link_workspace', to='app.Area')),
                ('business', models.ManyToManyField(blank=True, related_name='business_link_workspace', to='app.Business')),
                ('department', models.ManyToManyField(blank=True, related_name='department_link_workspace', to='app.Department')),
                ('module', models.ManyToManyField(blank=True, related_name='module_link_workspace', to='app.Module')),
                ('plant', models.ManyToManyField(blank=True, related_name='plant_link_workspace', to='app.Plant')),
            ],
        ),
    ]
