# Generated by Django 3.2.7 on 2021-09-14 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20210914_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='officeLocation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
