# Generated by Django 3.2.7 on 2021-09-14 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_user_officelocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='default_workspace',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
