# Generated by Django 3.2.7 on 2021-09-14 18:44

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_user_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='background',
            field=colorfield.fields.ColorField(default='#FF0000', max_length=18),
        ),
        migrations.AlterField(
            model_name='link',
            name='color',
            field=colorfield.fields.ColorField(default='#FF0000', max_length=18),
        ),
    ]
