# Generated by Django 3.2.7 on 2021-09-15 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20210914_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='display_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
