# Generated by Django 3.2.7 on 2021-09-16 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_user_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkworkspace',
            name='style',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
