# Generated by Django 3.2.7 on 2021-09-16 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_linkworkspace_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='workspace_style',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
