# Generated by Django 3.2.7 on 2021-09-16 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20210916_0701'),
    ]

    operations = [
        migrations.AddField(
            model_name='sidebar',
            name='sidebar_view',
            field=models.ManyToManyField(blank=True, related_name='sidebar_views', to='app.SidebarView'),
        ),
        migrations.DeleteModel(
            name='SidebarItem',
        ),
    ]
