# Generated by Django 3.2.7 on 2021-09-20 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_auto_20210916_0757'),
    ]

    operations = [
        migrations.CreateModel(
            name='SidebarLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('area', models.ManyToManyField(blank=True, related_name='area_sidebarlinks', to='app.Area')),
                ('business', models.ManyToManyField(blank=True, related_name='business_sidebarlinks', to='app.Business')),
                ('department', models.ManyToManyField(blank=True, related_name='department_sidebarlinks', to='app.Department')),
                ('link', models.ManyToManyField(blank=True, related_name='link_sidebarlinks', to='app.Link')),
                ('module', models.ManyToManyField(blank=True, related_name='module_sidebarlinks', to='app.Module')),
                ('plant', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='plant_sidebarlinks', to='app.plant')),
            ],
        ),
        migrations.DeleteModel(
            name='Sidebar',
        ),
    ]
