# Generated by Django 3.2.7 on 2021-09-20 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_auto_20210920_0815'),
    ]

    operations = [
        migrations.AddField(
            model_name='sidebarlinks',
            name='to',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
