# Generated by Django 3.2.7 on 2021-09-30 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_sidebarlinks_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sidebarlinks',
            name='to',
        ),
        migrations.RemoveField(
            model_name='stream',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='stream',
            name='report',
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('owner', models.ManyToManyField(blank=True, related_name='owner_slide', to='app.User')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slide_plant', to='app.plant')),
                ('report', models.ManyToManyField(blank=True, related_name='report_slide', to='app.Report')),
            ],
        ),
        migrations.AddField(
            model_name='stream',
            name='slide',
            field=models.ManyToManyField(blank=True, related_name='slide_stream', to='app.Slide'),
        ),
    ]
