# Generated by Django 3.2.7 on 2021-10-03 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_auto_20210930_0902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pod',
            name='stream',
        ),
        migrations.AddField(
            model_name='pod',
            name='stream',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stream_pod', to='app.stream'),
        ),
    ]
