# Generated by Django 3.2.7 on 2021-10-03 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_auto_20211003_0718'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='show_header',
            field=models.BooleanField(default=False),
        ),
    ]
