# Generated by Django 3.2.7 on 2021-10-03 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_stream_show_header'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='link',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='tag_link', to='app.Tag'),
        ),
        migrations.AddField(
            model_name='linkworkspace',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='tag_link_workspace', to='app.Tag'),
        ),
        migrations.AddField(
            model_name='pod',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='tag_pod', to='app.Tag'),
        ),
        migrations.AddField(
            model_name='report',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='tag_report', to='app.Tag'),
        ),
        migrations.AddField(
            model_name='sidebarlinks',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='tag_sidebarlinks', to='app.Tag'),
        ),
        migrations.AddField(
            model_name='stream',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='tag_stream', to='app.Tag'),
        ),
    ]
