# Generated by Django 3.2.7 on 2021-10-03 13:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_auto_20211003_0820'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slide',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
