# Generated by Django 3.2.7 on 2021-10-04 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_auto_20211003_0959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slide',
            name='report',
        ),
        migrations.AddField(
            model_name='slide',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_slide', to='app.report'),
        ),
    ]
