# Generated by Django 3.2.7 on 2021-10-05 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_rename_page_report_tab'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='tab',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
