# Generated by Django 3.2.7 on 2021-10-06 12:29

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_alter_report_tab'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='header_color',
            field=colorfield.fields.ColorField(default='#FFFFFF', max_length=18),
        ),
    ]
