# Generated by Django 3.2.7 on 2021-10-06 12:30

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_stream_header_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='header_color',
            field=colorfield.fields.ColorField(default='#0C00A4', max_length=18),
        ),
    ]
